/*
 Navicat PostgreSQL Data Transfer

 Source Server         : Local
 Source Server Type    : PostgreSQL
 Source Server Version : 110001 (110001)
 Source Host           : localhost:5432
 Source Catalog        : devstaff
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 110001 (110001)
 File Encoding         : 65001

 Date: 31/07/2024 23:37:36
*/


-- ----------------------------
-- Table structure for crop_type
-- ----------------------------
DROP TABLE IF EXISTS "public"."crop_type";
CREATE TABLE "public"."crop_type" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of crop_type
-- ----------------------------
INSERT INTO "public"."crop_type" VALUES (1, 'Potato');
INSERT INTO "public"."crop_type" VALUES (2, 'Corn');
INSERT INTO "public"."crop_type" VALUES (3, 'Rice');
INSERT INTO "public"."crop_type" VALUES (4, 'Weat');
INSERT INTO "public"."crop_type" VALUES (5, 'Cucumber');
INSERT INTO "public"."crop_type" VALUES (6, 'Tomato');

-- ----------------------------
-- Auto increment value for crop_type
-- ----------------------------
SELECT setval('"public"."crop_type_id_seq"', 8, true);

-- ----------------------------
-- Primary Key structure for table crop_type
-- ----------------------------
ALTER TABLE "public"."crop_type" ADD CONSTRAINT "crop_type_pkey" PRIMARY KEY ("id");
