/*
 Navicat PostgreSQL Data Transfer

 Source Server         : Local
 Source Server Type    : PostgreSQL
 Source Server Version : 110001 (110001)
 Source Host           : localhost:5432
 Source Catalog        : devstaff
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 110001 (110001)
 File Encoding         : 65001

 Date: 31/07/2024 23:37:45
*/


-- ----------------------------
-- Table structure for farm
-- ----------------------------
DROP TABLE IF EXISTS "public"."farm";
CREATE TABLE "public"."farm" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of farm
-- ----------------------------
INSERT INTO "public"."farm" VALUES (1, 'Farm Devstaff');

-- ----------------------------
-- Auto increment value for farm
-- ----------------------------
SELECT setval('"public"."farm_id_seq"', 3, true);

-- ----------------------------
-- Primary Key structure for table farm
-- ----------------------------
ALTER TABLE "public"."farm" ADD CONSTRAINT "farm_pkey" PRIMARY KEY ("id");
