/*
 Navicat PostgreSQL Data Transfer

 Source Server         : Local
 Source Server Type    : PostgreSQL
 Source Server Version : 110001 (110001)
 Source Host           : localhost:5432
 Source Catalog        : devstaff
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 110001 (110001)
 File Encoding         : 65001

 Date: 31/07/2024 23:37:53
*/


-- ----------------------------
-- Table structure for field
-- ----------------------------
DROP TABLE IF EXISTS "public"."field";
CREATE TABLE "public"."field" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "farm_id" int8
)
;

-- ----------------------------
-- Records of field
-- ----------------------------
INSERT INTO "public"."field" VALUES (1, 'Field Devstaff West', 1);

-- ----------------------------
-- Auto increment value for field
-- ----------------------------
SELECT setval('"public"."field_id_seq"', 3, true);

-- ----------------------------
-- Primary Key structure for table field
-- ----------------------------
ALTER TABLE "public"."field" ADD CONSTRAINT "field_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table field
-- ----------------------------
ALTER TABLE "public"."field" ADD CONSTRAINT "fkiamf9l68wupiaj7ohqto9ov5g" FOREIGN KEY ("farm_id") REFERENCES "public"."farm" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
