/*
 Navicat PostgreSQL Data Transfer

 Source Server         : Local
 Source Server Type    : PostgreSQL
 Source Server Version : 110001 (110001)
 Source Host           : localhost:5432
 Source Catalog        : devstaff
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 110001 (110001)
 File Encoding         : 65001

 Date: 31/07/2024 23:38:00
*/


-- ----------------------------
-- Table structure for harvest
-- ----------------------------
DROP TABLE IF EXISTS "public"."harvest";
CREATE TABLE "public"."harvest" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "actual_product_amount" float8,
  "season" varchar(255) COLLATE "pg_catalog"."default",
  "crop_type_id" int8,
  "field_id" int8
)
;

-- ----------------------------
-- Records of harvest
-- ----------------------------
INSERT INTO "public"."harvest" VALUES (1, 200, 'SUMMER', 1, 1);
INSERT INTO "public"."harvest" VALUES (2, 500, 'WINTER', 1, 1);

-- ----------------------------
-- Auto increment value for harvest
-- ----------------------------
SELECT setval('"public"."harvest_id_seq"', 3, true);

-- ----------------------------
-- Checks structure for table harvest
-- ----------------------------
ALTER TABLE "public"."harvest" ADD CONSTRAINT "harvest_season_check" CHECK (((season)::text = ANY ((ARRAY['SPRING'::character varying, 'SUMMER'::character varying, 'AUTUMN'::character varying, 'WINTER'::character varying])::text[])));

-- ----------------------------
-- Primary Key structure for table harvest
-- ----------------------------
ALTER TABLE "public"."harvest" ADD CONSTRAINT "harvest_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table harvest
-- ----------------------------
ALTER TABLE "public"."harvest" ADD CONSTRAINT "fkf88phm05cgj4166w4gtnb2qg3" FOREIGN KEY ("crop_type_id") REFERENCES "public"."crop_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."harvest" ADD CONSTRAINT "fkm0ypbbs2cgvc7n9v7q821i5fq" FOREIGN KEY ("field_id") REFERENCES "public"."field" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
