/*
 Navicat PostgreSQL Data Transfer

 Source Server         : Local
 Source Server Type    : PostgreSQL
 Source Server Version : 110001 (110001)
 Source Host           : localhost:5432
 Source Catalog        : devstaff
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 110001 (110001)
 File Encoding         : 65001

 Date: 31/07/2024 23:38:05
*/


-- ----------------------------
-- Table structure for plantation
-- ----------------------------
DROP TABLE IF EXISTS "public"."plantation";
CREATE TABLE "public"."plantation" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "expected_product_amount" float8,
  "planting_area" float8,
  "season" varchar(255) COLLATE "pg_catalog"."default",
  "crop_type_id" int8,
  "field_id" int8
)
;

-- ----------------------------
-- Records of plantation
-- ----------------------------
INSERT INTO "public"."plantation" VALUES (1, 500, 550, 'WINTER', 1, 1);
INSERT INTO "public"."plantation" VALUES (2, 200, 300, 'SUMMER', 1, 1);

-- ----------------------------
-- Auto increment value for plantation
-- ----------------------------
SELECT setval('"public"."plantation_id_seq"', 3, true);

-- ----------------------------
-- Checks structure for table plantation
-- ----------------------------
ALTER TABLE "public"."plantation" ADD CONSTRAINT "plantation_season_check" CHECK (((season)::text = ANY ((ARRAY['SPRING'::character varying, 'SUMMER'::character varying, 'AUTUMN'::character varying, 'WINTER'::character varying])::text[])));

-- ----------------------------
-- Primary Key structure for table plantation
-- ----------------------------
ALTER TABLE "public"."plantation" ADD CONSTRAINT "plantation_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table plantation
-- ----------------------------
ALTER TABLE "public"."plantation" ADD CONSTRAINT "fk6yoi9h2m9nkabkeim1bd50b5q" FOREIGN KEY ("crop_type_id") REFERENCES "public"."crop_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."plantation" ADD CONSTRAINT "fk8trnbh75gxxb3vyibks8xo279" FOREIGN KEY ("field_id") REFERENCES "public"."field" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
